export const certificates = [
  {
    id: 1,
    title: "ISC2 CC Course Conclusion & Final Assessment",
    issuer: "ISC2",
    date: "2026",
    color: "#FF9900",
    image: "/images/cyber.png",
    category: "Cloud",
  },
  {
    id: 2,
    title: "IBM AI Agent Developer",
    issuer: "IBM",
    date: "2026",
    color: "#0062FF",
    image: "/images/Build-an-AI-Agent.png",
    category: "AI",
  },
  {
    id: 3,
    title: "Cisco IT Support",
    issuer: "Cisco",
    date: "2026",
    color: "#049fd9",
    image: "/images/cisco.png",
    category: "IT",
  },
  {
    id: 4,
    title: "Android App Development",
    issuer: "Simplilearn",
    date: "2026",
    color: "#C4874A",
    image: "/images/mobile-sertifikat.png",
    category: "Mobile",
  },
  {
    id: 5,
    title: "Flutter and Dart: Developing iOS, Android, and Mobile Apps",
    issuer: "Coursera",
    date: "2026",
    color: "#FF6B35",
    image: "/images/courseramobile.png",
    category: "AI",
  },
  {
    id: 6,
    title: "Introduction to MS Excel",
    issuer: "Microsoft",
    date: "2026",
    color: "#00d2ff",
    image: "/images/excel.png",
    category: "Data",
  },
  {
    id: 7,
    title: "Flutter Beginner",
    issuer: "Course Provider",
    date: "2024",
    color: "#02569B",
    image: "/images/flutterbeginer.jpg",
    category: "Mobile",
  },
  {
    id: 8,
    title: "Dart and Flutter",
    issuer: "Course Provider",
    date: "2024",
    color: "#02569B",
    image: "/images/Dart and Flutter_page-0001.jpg",
    category: "Mobile",
  },
  {
    id: 9,
    title: "Complete Python",
    issuer: "Course Provider",
    date: "2024",
    color: "#306998",
    image: "/images/Complete Python_page-0001.jpg",
    category: "Backend",
  },
  {
    id: 10,
    title: "Large Language Models (LLM)",
    issuer: "Course Provider",
    date: "2024",
    color: "#8A2BE2",
    image: "/images/llm.png",
    category: "AI",
  },
  {
    id: 11,
    title: "Lab: Troubleshoot Your Code Using IBM Bob",
    issuer: "IBM SkillsBuild",
    date: "2026",
    color: "#0F62FE",
    image: "/images/ibmbob.png",
    category: "AI",
  },
];
